// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8RLGcuLe68RuBcQXxfUGXvQ-nGhU83R0',
    appId: '1:473182681993:web:5560a9c624061cd29f7f58',
    messagingSenderId: '473182681993',
    projectId: 'guess-duel-3b9f1',
    authDomain: 'guess-duel-3b9f1.firebaseapp.com',
    storageBucket: 'guess-duel-3b9f1.firebasestorage.app',
    measurementId: 'G-MPQY00H5BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7UxaM1U5sQnVUuc5v_HioD1Y770UzOLQ',
    appId: '1:473182681993:android:f3d80c4cb100e4419f7f58',
    messagingSenderId: '473182681993',
    projectId: 'guess-duel-3b9f1',
    storageBucket: 'guess-duel-3b9f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2P6Bv8Nyu3jeiT-dQaf1xB41E_6it22A',
    appId: '1:473182681993:ios:e3fbf9ef1ea8bfa39f7f58',
    messagingSenderId: '473182681993',
    projectId: 'guess-duel-3b9f1',
    storageBucket: 'guess-duel-3b9f1.firebasestorage.app',
    iosBundleId: 'com.example.guessDuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2P6Bv8Nyu3jeiT-dQaf1xB41E_6it22A',
    appId: '1:473182681993:ios:e3fbf9ef1ea8bfa39f7f58',
    messagingSenderId: '473182681993',
    projectId: 'guess-duel-3b9f1',
    storageBucket: 'guess-duel-3b9f1.firebasestorage.app',
    iosBundleId: 'com.example.guessDuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8RLGcuLe68RuBcQXxfUGXvQ-nGhU83R0',
    appId: '1:473182681993:web:551a69646b2b26579f7f58',
    messagingSenderId: '473182681993',
    projectId: 'guess-duel-3b9f1',
    authDomain: 'guess-duel-3b9f1.firebaseapp.com',
    storageBucket: 'guess-duel-3b9f1.firebasestorage.app',
    measurementId: 'G-RZ3YCFJT83',
  );
}
