# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Const suggestions
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # Flutter clean code
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true

    # # Optional style rules
    # prefer_single_quotes: true