import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:guess_duel/screens/offline%20game%20screens/create_offline_game/widgets/custom_setup_panel.dart';
import 'package:guess_duel/screens/offline%20game%20screens/create_offline_game/widgets/difficulty_card.dart';
import 'package:guess_duel/Widgets/glow_button.dart';
import 'package:guess_duel/cubit/Create%20offline%20game/create_offline_game_cubit.dart';
import 'package:guess_duel/cubit/Create%20offline%20game/create_offline_game_state.dart';
import 'package:guess_duel/models/offline_game_model.dart';
import 'package:guess_duel/screens/offline%20game%20screens/game_screen.dart/solo_challenge_screen.dart';

class OfflineCreateBs extends StatefulWidget {
  const OfflineCreateBs({super.key});

  /// Helper to show this widget as a BottomSheet cleanly
  static Future<Map<String, dynamic>?> show(BuildContext context) {
    return showModalBottomSheet<Map<String, dynamic>>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => const OfflineCreateBs(),
    );
  }

  @override
  State<OfflineCreateBs> createState() => _OfflineCreateBsState();
}

class _OfflineCreateBsState extends State<OfflineCreateBs> {
  final DifficultyLevel _selectedLevel = DifficultyLevel.normal;
  bool _isCustomExpanded = false;

  // Custom Setup State

  OfflineGameModel gameModel = const OfflineGameModel();

  void _selectDifficulty(DifficultyLevel level) {
    setState(() {
      gameModel = gameModel.copyWith(difficultyLevel: level);
      _isCustomExpanded = false;

      switch (level) {
        case DifficultyLevel.easy:
          gameModel = gameModel.copyWith(
            digits: 4,
            attempts: 15,
            timer: TimerType.unlimited,
            allowRepeatedDigits: false,
          );
          break;

        case DifficultyLevel.normal:
          gameModel = gameModel.copyWith(
            digits: 4,
            attempts: 10,
            timer: TimerType.unlimited,
            allowRepeatedDigits: false,
          );

          break;
        case DifficultyLevel.hard:
          gameModel = gameModel.copyWith(
            digits: 4,
            attempts: 8,
            timer: TimerType.fiveMinutes,
            allowRepeatedDigits: false,
          );

          break;
        case DifficultyLevel.extreme:
          gameModel = gameModel.copyWith(
            digits: 5,
            attempts: 9,
            timer: TimerType.twoMinutes,
            allowRepeatedDigits: false,
          );

          break;
        case DifficultyLevel.custom:
          _isCustomExpanded = true;
          break;
      }
    });
  }

  void _toggleCustomSetup() {
    setState(() {
      _isCustomExpanded = !_isCustomExpanded;
      if (_isCustomExpanded) {
        gameModel = gameModel.copyWith(difficultyLevel: DifficultyLevel.custom);
      }
    });
  }

  void _startGame() async {
    await context.read<CreateOfflineGameCubit>().createOfflineGame(gameModel);
  }

  @override
  Widget build(BuildContext context) {
    final mediaQuery = MediaQuery.of(context);
    final maxHeight = mediaQuery.size.height * 0.9;

    return Container(
      constraints: BoxConstraints(maxHeight: maxHeight),
      decoration: const BoxDecoration(
        color: Color(0xFF131313),
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
        border: Border(top: BorderSide(color: Color(0x4D4D4356), width: 1)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Drag Handle
          const SizedBox(height: 12),
          Container(
            width: 48,
            height: 6,
            decoration: BoxDecoration(
              color: const Color(0x804D4356),
              borderRadius: BorderRadius.circular(3),
            ),
          ),
          const SizedBox(height: 16),

          // Header Title & Subtitle
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Solo Challenge',
                  style: GoogleFonts.spaceGrotesk(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                    color: const Color(0xFFE5E2E1),
                    letterSpacing: -0.5,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Guess the secret number generated by the game.',
                  style: GoogleFonts.manrope(
                    fontSize: 14,
                    color: const Color(0xFFCFC2D9).withValues(alpha: 0.8),
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 16),

          // Scrollable Content
          Flexible(
            child: SingleChildScrollView(
              padding: const EdgeInsets.fromLTRB(24, 0, 24, 100),
              physics: const BouncingScrollPhysics(),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Preset Difficulty Cards
                  DifficultyCard(
                    title: DifficultyLevel.easy.name,
                    isSelected:
                        gameModel.difficultyLevel == DifficultyLevel.easy,
                    accentColor: const Color(0xFF00EEFC),
                    offlineGameModel: const OfflineGameModel(
                      difficultyLevel: DifficultyLevel.easy,
                      digits: 4,
                      attempts: 15,
                      timer: TimerType.unlimited,
                    ),
                    onTap: () => _selectDifficulty(DifficultyLevel.easy),
                  ),
                  DifficultyCard(
                    isSelected:
                        gameModel.difficultyLevel == DifficultyLevel.normal,
                    title: DifficultyLevel.normal.name,
                    offlineGameModel: const OfflineGameModel(
                      difficultyLevel: DifficultyLevel.normal,
                      digits: 4,
                      attempts: 10,
                      timer: TimerType.unlimited,
                    ),
                    accentColor: const Color(0xFFDAB9FF),
                    onTap: () => _selectDifficulty(DifficultyLevel.normal),
                  ),
                  DifficultyCard(
                    isSelected:
                        gameModel.difficultyLevel == DifficultyLevel.hard,
                    title: DifficultyLevel.hard.name,
                    accentColor: const Color(0xFFB8C8DA),
                    onTap: () => _selectDifficulty(DifficultyLevel.hard),
                    offlineGameModel: const OfflineGameModel(
                      difficultyLevel: DifficultyLevel.hard,
                      digits: 4,
                      attempts: 8,
                      timer: TimerType.fiveMinutes,
                    ),
                  ),
                  DifficultyCard(
                    isSelected:
                        gameModel.difficultyLevel == DifficultyLevel.extreme,
                    title: DifficultyLevel.extreme.name,
                    offlineGameModel: const OfflineGameModel(
                      difficultyLevel: DifficultyLevel.extreme,
                      digits: 5,
                      attempts: 9,
                      timer: TimerType.twoMinutes,
                    ),
                    accentColor: const Color(0xFFFFB4AB),

                    onTap: () => _selectDifficulty(DifficultyLevel.extreme),
                  ),

                  const SizedBox(height: 8),

                  // Custom Setup Header Tile
                  Container(
                    decoration: BoxDecoration(
                      color: const Color(0x99201F1F),
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(
                        color: _selectedLevel == DifficultyLevel.custom
                            ? const Color(0xFFDAB9FF)
                            : const Color(0x1A988CA2),
                        style: BorderStyle.solid,
                      ),
                    ),
                    child: Material(
                      color: Colors.transparent,
                      child: InkWell(
                        onTap: _toggleCustomSetup,
                        borderRadius: BorderRadius.circular(20),
                        child: Padding(
                          padding: const EdgeInsets.all(16),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Row(
                                children: [
                                  Container(
                                    width: 40,
                                    height: 40,
                                    decoration: BoxDecoration(
                                      color: const Color(0xFF353534),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    child: const Icon(
                                      Icons.tune_rounded,
                                      color: Color(0xFFE5E2E1),
                                    ),
                                  ),
                                  const SizedBox(width: 12),
                                  Text(
                                    'Custom Setup',
                                    style: GoogleFonts.spaceGrotesk(
                                      fontSize: 18,
                                      fontWeight: FontWeight.bold,
                                      color: const Color(0xFFE5E2E1),
                                    ),
                                  ),
                                ],
                              ),
                              AnimatedRotation(
                                turns: _isCustomExpanded ? 0.5 : 0.0,
                                duration: const Duration(milliseconds: 300),
                                child: const Icon(
                                  Icons.expand_more_rounded,
                                  color: Color(0xFFE5E2E1),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),

                  // Collapsible Custom Setup Panel
                  AnimatedCrossFade(
                    firstChild: const SizedBox(width: double.infinity),
                    secondChild: CustomSetupPanel(
                      selectedDigits: gameModel.digits,
                      onDigitsChanged: (val) => setState(
                        () => gameModel = gameModel.copyWith(digits: val),
                      ),
                      maxAttempts: gameModel.attempts,
                      onAttemptsChanged: (val) => setState(
                        () => gameModel = gameModel.copyWith(attempts: val),
                      ),
                      selectedTimer: gameModel.timer.label,
                      onTimerChanged: (val) => setState(() {
                        gameModel = gameModel.copyWith(
                          timer: TimerTypeExtension.fromName(val),
                        );
                      }),
                      allowRepeatedDigits: gameModel.allowRepeatedDigits,
                      onAllowRepeatedChanged: (val) => setState(
                        () => gameModel = gameModel.copyWith(
                          allowRepeatedDigits: val,
                        ),
                      ),
                    ),
                    crossFadeState: _isCustomExpanded
                        ? CrossFadeState.showSecond
                        : CrossFadeState.showFirst,
                    duration: const Duration(milliseconds: 300),
                  ),
                ],
              ),
            ),
          ),

          // Sticky Bottom Action Bar
          Container(
            padding: EdgeInsets.fromLTRB(
              24,
              16,
              24,
              16 + mediaQuery.padding.bottom,
            ),
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [
                  Colors.transparent,
                  Color(0xFF131313),
                  Color(0xFF131313),
                ],
              ),
            ),
            child: BlocConsumer<CreateOfflineGameCubit, CreateOfflineGameState>(
              listener: (context, state) {
                if (state.isCreated) {
                  Get.to(
                    () => SoloChallengeScreen(
                      offlineGameModel: state.offlineGameModel,
                    ),
                  );
                }
              },
              builder: (context, state) {
                return GlowButton(
                  text: 'START GAME',
                  onPressed: _startGame,
                  isEnabled: state.isLoading == false,
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
